apiVersion: v1
kind: Pod
metadata:
  name: pdf-test
  labels:
    app: myapp
spec:
  containers:
    - name: pdf-test
      image: nogisora/pdf-test-ver3:latest
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: pdf-test
spec:
  type: NodePort
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
      nodePort: 31080
  selector:
    app: myapp
