apiVersion: v1
kind: Pod
metadata:
  name: upload-test
  labels:
    app: myapp2
spec:
  containers:
    - name: demo-container
      image: nogisora/pdf-test-ver4:latest
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: upload-test
spec:
  type: NodePort
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8085
      targetPort: 80
      nodePort: 31081
  selector:
    app: myapp2
