apiVersion: v1
kind: Pod
metadata:
  name: upload-test
  labels:
    app: myupload
spec:
  containers:
    - name: uploadcontainer
      image: nogisora/upload-test:latest
      imagePullPolicy: Always
      resources:
        requests:
          cpu: "500m"
        limits:
          cpu: "500m"
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: upload-service
  labels:
    app: myupload
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 80
      nodePort: 31091
  selector:
    app: myupload
